version: "3"

volumes:
  postgresdb_volume:

services:
  postgresdb:
    build: ./pkg
    restart: always
    container_name: postgres
    volumes:
      - postgresdb_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  snippetbox:
    build: .
    depends_on:
      - postgresdb
    restart: always
    container_name: gosnippet
    ports:
      - 4000:4000